package ventanas;

import base.CandidatoDBHelper;
import base.GrupoDBHelper;
import clase.Asesor;
import clase.Candidato;
import clase.Grupo;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.EtchedBorder;

/**
 *
 * @author Parker
 */
public class Grupos extends javax.swing.JFrame {
    /**
    * se utiliza para poner algo de su información y para distinguir si un
    * candidato esta viendo la ventana.
    */
    private Candidato vistaCandidato;

    /**
    * se utiliza para poner algo de su información y para distinguir si un
    * asesor esta viendo la ventana.
    */
    private Asesor vistaAsesor;

    /**
     * Creates new form Grupos.
     */
    public Grupos() {
        initComponents();
        inicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPanel = new javax.swing.JScrollPane();
        jPanelCandidatos = new javax.swing.JPanel();
        jBtAtras = new javax.swing.JButton();
        jTbPnGrupos = new javax.swing.JTabbedPane();
        jLbGrupo = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanelCandidatosLayout = new javax.swing.GroupLayout(jPanelCandidatos);
        jPanelCandidatos.setLayout(jPanelCandidatosLayout);
        jPanelCandidatosLayout.setHorizontalGroup(
            jPanelCandidatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelCandidatosLayout.setVerticalGroup(
            jPanelCandidatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jScrollPanel.setViewportView(jPanelCandidatos);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seminario de Apoyo a la titulación");

        jBtAtras.setText("Atrás");
        jBtAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAtrasActionPerformed(evt);
            }
        });

        jLbGrupo.setText("jLbGrupo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLbGrupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 338, Short.MAX_VALUE)
                        .addComponent(jBtAtras))
                    .addComponent(jTbPnGrupos))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTbPnGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtAtras)
                    .addComponent(jLbGrupo))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAtrasActionPerformed
        JFrame ventana;

        if (vistaCandidato != null) {
            ventana = new IniciarSesion();
        } else {
            ventana = new PerfilAsesor();
            ((PerfilAsesor) ventana).setAsesor(vistaAsesor);
        }

        ventana.setLocationRelativeTo(this);
        ventana.show();
        this.dispose();
    }//GEN-LAST:event_jBtAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grupos().setVisible(true);
            }
        });
    }

    /**
    * Funcion que pone los valores por defecto.
    */
    private void inicio() {
        vistaCandidato = null;
        vistaAsesor = null;
        jLbGrupo.setVisible(false);

        // Se recuperan todos los grupos existentes en la base de datos.
        GrupoDBHelper helperGrupo = new GrupoDBHelper();
        ArrayList < Grupo > grupos = helperGrupo.getGrupos();

        for (Grupo grupo : grupos) {
            // Se recuperan todos los candidatos que conforman ese grupo.
            CandidatoDBHelper helperCandidato = new CandidatoDBHelper();
            grupo = helperCandidato.getConGrupoIG(grupo);

            // Se crea el panel donde se mostraran los candidatos.
            jScrollPanel = new JScrollPane();
            jPanelCandidatos = new JPanel();
            jPanelCandidatos.setLayout(
                            new BoxLayout(jPanelCandidatos, BoxLayout.Y_AXIS));
            jScrollPanel.setViewportView(jPanelCandidatos);

            for (Candidato candidato : grupo.getCandidatos()) {
                /*
                * Se crea un panel que muestra a un solo candidato y
                * se pasa el candidato que mostrara.
                */
                CandidatoIG panelCandidato = new CandidatoIG();
                panelCandidato.setCandidato(candidato);
                panelCandidato.setAsesor(candidato.getAsesor());
                panelCandidato.vistaAsesor(false);

                // Formato al borde del panel
                panelCandidato.setBorder(
                        BorderFactory.createEtchedBorder(EtchedBorder.LOWERED));

                /*
                * Por último se agrega el panel de un candidato al panel
                * que mostrar la lista de candidatos sin grupo.
                */
                jPanelCandidatos.add(panelCandidato);
            }

            jTbPnGrupos.add("Grupo " + grupo.getNombre(), jScrollPanel);
        }
    }

    /**
    * Obtinen el candidato.
    *
    * @return       un Candidato, el quien esta viendo la ventana.
    */
    public final Candidato getVistaCandidato() {
        return vistaCandidato;
    }

    /**
    * Asigna un candidato.
    *
    * @param    vistaCandidatoX     el quien abrira la ventana
    *                               y se mostrara en que estado esta.
    */
    public final void setVistaCandidato(final Candidato vistaCandidatoX) {
        this.vistaCandidato = vistaCandidatoX;
        mostraGrupo();
    }

    /**
    * Obtinen el asesor.
    *
    * @return       un Asesor, el quien esta viendo la ventana.
    */
    public final Asesor getVistaAsesor() {
        return vistaAsesor;
    }

    /**
    * Asigna un asesor.
    *
    * @param    vistaAsesorX     el quien abrira la ventana.
    */
    public final void setVistaAsesor(final Asesor vistaAsesorX) {
        this.vistaAsesor = vistaAsesorX;
    }

    /**
    * Muestra en que grupo esta el candidto si es el caso de que inicio sesión.
    */
    private void mostraGrupo() {
        jLbGrupo.setVisible(true);
        jBtAtras.setText("Cerrar sesión");

        // Se consulta a la base de datos para saber el grupo del candidato.
        CandidatoDBHelper helper = new CandidatoDBHelper();
        String nombreGrupo = helper.getNombreGrupo(vistaCandidato);

        /*
        * Si la consulta devuelve que no esta en ningun grupo
        * se muestra un mensaje.
        */
        if (nombreGrupo.equals("")) {
            jLbGrupo.setText(vistaCandidato.getNombre()
                            + " te encuetras en espera de grupo");
            return;
        }

        // Delo contrario se mostrara el grupo.
        jLbGrupo.setText(vistaCandidato.getNombre()
                        + " te encuetras en el grupo: " + nombreGrupo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtAtras;
    private javax.swing.JLabel jLbGrupo;
    private javax.swing.JPanel jPanelCandidatos;
    private javax.swing.JScrollPane jScrollPanel;
    private javax.swing.JTabbedPane jTbPnGrupos;
    // End of variables declaration//GEN-END:variables
}
