package ventanas;

import base.AsesorDBHelper;
import base.CandidatoDBHelper;
import clase.Asesor;
import clase.Candidato;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.SwingConstants;

/**
 *
 * @author Parker
 */
public class IniciarSesion extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSesion.
     */
    public IniciarSesion() {
        initComponents();
        inicio(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbNombre = new javax.swing.JLabel();
        jTxtFNombre = new javax.swing.JTextField();
        jLbContrasena = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jBtRegistro = new javax.swing.JButton();
        jBtRegCandidato = new javax.swing.JButton();
        jBtRegAsesor = new javax.swing.JButton();
        jBtLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar sesión");

        jLbNombre.setText("Nombre");

        jTxtFNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtFNombreKeyPressed(evt);
            }
        });

        jLbContrasena.setText("Contraseña");

        jPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldKeyPressed(evt);
            }
        });

        jBtRegistro.setText("Registrarse");
        jBtRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtRegistroActionPerformed(evt);
            }
        });

        jBtRegCandidato.setText("Candidato");
        jBtRegCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtRegCandidatoActionPerformed(evt);
            }
        });

        jBtRegAsesor.setText("Asesor");
        jBtRegAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtRegAsesorActionPerformed(evt);
            }
        });

        jBtLogin.setText("Iniciar sesión");
        jBtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jBtRegCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtRegAsesor, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLbContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbNombre)
                            .addComponent(jTxtFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbContrasena)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jBtLogin)
                        .addGap(18, 18, 18)
                        .addComponent(jBtRegistro))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtRegCandidato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtRegAsesor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtRegistroActionPerformed
        JFrame ventana;

        /*
        * Se verifica el título de la ventana para saber si se resgistrara
        * candidato o asesor.
        */
        if ("Iniciar sesión > Candidato".equals(this.getTitle())) {
            ventana = new RegistroCandidato();
        } else {
            ventana = new RegistroAsesor();
        }

        ventana.setLocationRelativeTo(this);
        ventana.show();
        this.dispose();
    }//GEN-LAST:event_jBtRegistroActionPerformed

    private void jBtRegCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtRegCandidatoActionPerformed
        // Se verifica que texto tiene el boton para ver en que estado estas.
        if ("Candidato".equals(jBtRegCandidato.getText())) {
            inicio(false);
            jBtRegCandidato.setText("Atrás");
            jBtRegCandidato.setVisible(true);
            this.setTitle(this.getTitle() + " > Candidato");
            return;
        }

        inicio(true);
        this.setTitle("Iniciar sesión");
    }//GEN-LAST:event_jBtRegCandidatoActionPerformed

    private void jBtRegAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtRegAsesorActionPerformed
        // Se verifica que texto tiene el boton para ver en que estado estas.
        if ("Asesor".equals(jBtRegAsesor.getText())) {
            inicio(false);
            jBtRegAsesor.setText("Atrás");
            jBtRegAsesor.setVisible(true);
            this.setTitle(this.getTitle() + " > Asesor");
            return;
        }

        inicio(true);        
        this.setTitle("Iniciar sesión");
    }//GEN-LAST:event_jBtRegAsesorActionPerformed

    private void jBtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtLoginActionPerformed
        iniciarSecion();
    }//GEN-LAST:event_jBtLoginActionPerformed

    private void jTxtFNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFNombreKeyPressed
        colorText(Color.GRAY);
    }//GEN-LAST:event_jTxtFNombreKeyPressed

    private void jPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldKeyPressed
        colorText(Color.GRAY);

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            iniciarSecion();
        }
    }//GEN-LAST:event_jPasswordFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });
    }

    /**
    * Valores por defecto.
    *
    * @param    visibles    true aparecen dos botone de candidato y asesor,
    *                       false aparecen los botenes inicio de sesión y
    *                       registrarse con las cajas de texto nombre y
    *                       contraseña.
    */
    private void inicio(final boolean visibles) {
        String url = "";
        final int expander = 380;
        final int contraer = 320;

        // Tamaño de la ventana.
        final int tamanoEnY = 250;
        int tamanoEnX = expander;

        if (visibles) {
            tamanoEnX = contraer;
        }

        // Se coloca la ventana en medio de la pantalla y tamaño.
        this.setSize(new Dimension(tamanoEnX, tamanoEnY));

        jLbNombre.setVisible(!visibles);
        jLbContrasena.setVisible(!visibles);
        jTxtFNombre.setVisible(!visibles);
        jPasswordField.setVisible(!visibles);
        jBtLogin.setVisible(!visibles);
        jBtRegistro.setVisible(!visibles);
        jBtRegAsesor.setVisible(visibles);
        jBtRegCandidato.setVisible(visibles);

        jBtRegCandidato.setText("Candidato");
        url = "/Imagenes/candidato.png";
        ImageIcon imgCandidato = new ImageIcon(getClass().getResource(url));
        jBtRegCandidato.setIcon(imgCandidato);
        jBtRegAsesor.setText("Asesor");
        url = "/Imagenes/asesor.png";
        ImageIcon imgAsesor = new ImageIcon(getClass().getResource(url));
        jBtRegAsesor.setIcon(imgAsesor);
        jBtRegCandidato.setHorizontalTextPosition(SwingConstants.CENTER);
        jBtRegCandidato.setVerticalTextPosition(SwingConstants.BOTTOM);
        jBtRegAsesor.setHorizontalTextPosition(SwingConstants.CENTER);
        jBtRegAsesor.setVerticalTextPosition(SwingConstants.BOTTOM);
        jTxtFNombre.setText("");
        jPasswordField.setText("");
        colorText(Color.GRAY);
    }

    /**
    * Cambia el color del borde de las cajas de texto de nombre y contraseña.
    *
    * @param    color   de borde para las cajas de texto nombre y contraseña.
    */
    private void colorText(final Color color) {
        jTxtFNombre.setBorder(BorderFactory.createLineBorder(color, 1));
        jPasswordField.setBorder(BorderFactory.createLineBorder(color, 1));
    }

    /**
    * inicio de sesión distinguiendo quien lo solicita.
    */
    private void iniciarSecion() {
        /*
        * Se verifica el título de la ventana para saber si se resgistrara
        * candidato o asesor.
        */
        if ("Iniciar sesión > Candidato".equals(this.getTitle())) {
            // Se obtiene un canditado por su contraseña.
            CandidatoDBHelper helper = new CandidatoDBHelper();
            Candidato candidato = helper.getCandidato(jPasswordField.getText());

            /*
            * Se verifica que su nombre y contraseña sean las del candidato.
            * Si lo es se abre la ventana de grupos.
            */
            String nombre = jTxtFNombre.getText().toUpperCase();
            if (candidato != null && candidato.getNombre().equals(nombre)) {
                Grupos ventana = new Grupos();
                ventana.setVistaCandidato(candidato);
                ventana.setLocationRelativeTo(this);
                ventana.show();
                this.dispose();
            }

            /*
            * De lo contrario se marca en rojo las cajas de texto,
            * indicando que estan mal los datos.
            */
            colorText(Color.RED);
            return;
        }

        AsesorDBHelper helper = new AsesorDBHelper();
        Asesor asesor = helper.getAsesor(jPasswordField.getText());

        /*
        * Se verifica que su nombre y contraseña sean las del asesor.
        * Si lo es se abre la ventana del perfil del asesor.
        */
        String nombre = jTxtFNombre.getText().toUpperCase();
        if (asesor != null && asesor.getNombre().equals(nombre)) {
            PerfilAsesor ventana = new PerfilAsesor();
            ventana.setLocationRelativeTo(this);
            ventana.setAsesor(asesor);
            ventana.show();
            this.dispose();
        }

        /*
        * De lo contrario se marca en rojo las cajas de texto,
        * indicando que estan mal los datos.
        */
        colorText(Color.RED);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtLogin;
    private javax.swing.JButton jBtRegAsesor;
    private javax.swing.JButton jBtRegCandidato;
    private javax.swing.JButton jBtRegistro;
    private javax.swing.JLabel jLbContrasena;
    private javax.swing.JLabel jLbNombre;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTxtFNombre;
    // End of variables declaration//GEN-END:variables
}
