/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import BaseDatos.CandidatoDBHelper;
import Clases.Candidato;
import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Parker
 */
public class RegistroCandidato extends javax.swing.JFrame {
    File cartaCompromiso;
    File cartaMotivos;
    /**
     * Creates new form RegistroCandidato
     */
    public RegistroCandidato() {
        initComponents();
        Inicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGroupTrabaja = new javax.swing.ButtonGroup();
        jBtAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTxtFNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtFApPaterno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtFApMaterno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtFMatricula1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtFEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtFCelular = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxtFCarrera = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTxtFTemaTesis = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxtFDirectorTesis = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jRadBtSi = new javax.swing.JRadioButton();
        jRadBtNo = new javax.swing.JRadioButton();
        jLbLugarTrabajo = new javax.swing.JLabel();
        jTxtFLugarTrabajo = new javax.swing.JTextField();
        jLbHrTrabajo = new javax.swing.JLabel();
        jTxtFHrTrabajo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jBtCartaCompromiso = new javax.swing.JButton();
        jBtCartaMotivos = new javax.swing.JButton();
        jBtAceptar = new javax.swing.JButton();
        jLbCartaCompromiso = new javax.swing.JLabel();
        jLbCartaMotivos = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLbFoto = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jTxtFMatricula2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTxtFMatricula3 = new javax.swing.JTextField();
        jTxtFGeneracion = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jSpnCreditos = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de candidato");

        jBtAtras.setText("Atrás");
        jBtAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAtrasActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido Paterno");

        jLabel3.setText("Apellido Materno");

        jLabel4.setText("Matricula");

        jLabel5.setText("Correo electrónico");

        jLabel6.setText("Teléfono celular");

        jLabel7.setText("Carrera");

        jLabel8.setText("Generación");

        jLabel9.setText("Tema de tesis");

        jLabel10.setText("Director de tesis");

        jLabel11.setText("Trabaja");

        btGroupTrabaja.add(jRadBtSi);
        jRadBtSi.setText("Si");
        jRadBtSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadBtSiActionPerformed(evt);
            }
        });

        btGroupTrabaja.add(jRadBtNo);
        jRadBtNo.setText("No");
        jRadBtNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadBtNoActionPerformed(evt);
            }
        });

        jLbLugarTrabajo.setText("Lugar de trabajo");

        jLbHrTrabajo.setText("Horario de trabajo");

        jLabel14.setText("Carta compromiso");

        jLabel15.setText("Carta exposición");

        jBtCartaCompromiso.setText("Subir");
        jBtCartaCompromiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCartaCompromisoActionPerformed(evt);
            }
        });

        jBtCartaMotivos.setText("Subir");
        jBtCartaMotivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCartaMotivosActionPerformed(evt);
            }
        });

        jBtAceptar.setText("Aceptar");
        jBtAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAceptarActionPerformed(evt);
            }
        });

        jLbCartaCompromiso.setText("jLbCartaCompromiso");

        jLbCartaMotivos.setText("jLbCartaMotivos");

        jLabel16.setText("de motivos");

        jLbFoto.setText("jLbFoto");
        jLbFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLbFotoMousePressed(evt);
            }
        });

        jLabel12.setText("Contraseña");

        jLabel13.setText("-");

        jLabel17.setText("-");

        jLabel18.setText("Creditos");

        jLabel19.setText("%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16))
                                .addGap(18, 30, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtCartaMotivos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLbCartaMotivos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtCartaCompromiso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLbCartaCompromiso, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jTxtFMatricula1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTxtFMatricula2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel17)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTxtFMatricula3))
                                        .addComponent(jTxtFGeneracion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxtFEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(jRadBtSi)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadBtNo))
                                        .addComponent(jTxtFHrTrabajo)
                                        .addComponent(jTxtFLugarTrabajo)
                                        .addComponent(jTxtFDirectorTesis)
                                        .addComponent(jTxtFTemaTesis)
                                        .addComponent(jTxtFCarrera)
                                        .addComponent(jTxtFCelular)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jSpnCreditos)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel19))))
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jBtAceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtAtras))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLbHrTrabajo)
                                    .addComponent(jLbLugarTrabajo)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel4)
                                    .addComponent(jLbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTxtFApPaterno)
                                            .addComponent(jTxtFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel3))
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jPasswordField)
                                            .addComponent(jTxtFApMaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))))
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTxtFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTxtFApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTxtFApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtFMatricula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTxtFMatricula2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jTxtFMatricula3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTxtFCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtFCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jSpnCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTxtFGeneracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTxtFTemaTesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTxtFDirectorTesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jRadBtSi)
                    .addComponent(jRadBtNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbLugarTrabajo)
                    .addComponent(jTxtFLugarTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbHrTrabajo)
                    .addComponent(jTxtFHrTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jBtCartaCompromiso)
                    .addComponent(jLbCartaCompromiso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtCartaMotivos)
                    .addComponent(jLbCartaMotivos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtAtras)
                    .addComponent(jBtAceptar))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAtrasActionPerformed
        IniciarSesion ventana = new IniciarSesion();
        ventana.setLocationRelativeTo(this);
        ventana.show();        
        this.dispose();
    }//GEN-LAST:event_jBtAtrasActionPerformed

    private void jRadBtSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadBtSiActionPerformed
        Trabajo(true);
    }//GEN-LAST:event_jRadBtSiActionPerformed

    private void jRadBtNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadBtNoActionPerformed
        Trabajo(false);
    }//GEN-LAST:event_jRadBtNoActionPerformed

    private void jBtAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAceptarActionPerformed
        //Se crea la conexión a la base de datos.
        CandidatoDBHelper helper = new CandidatoDBHelper();
        
        //Se capturan todos los datos ingresados en las cajas de texto y foto.
        ImageIcon foto = (ImageIcon)jLbFoto.getIcon();
        String nombre = jTxtFNombre.getText().toUpperCase();
        String apellidoPaterno = jTxtFApPaterno.getText().toUpperCase();
        String apellidoMaterno = jTxtFApMaterno.getText().toUpperCase();
        String contrasena = jPasswordField.getText();
        String valorTxt = jTxtFMatricula1.getText() + jTxtFMatricula2.getText() + jTxtFMatricula3.getText();
        int matricula = Integer.parseInt(valorTxt);
        String email = jTxtFEmail.getText();
        String carrera = jTxtFCarrera.getText().toUpperCase();
        int creditos = Integer.parseInt(jSpnCreditos.getValue().toString());
        String temaTesis = jTxtFTemaTesis.getText().toUpperCase();
        String directorTesis = jTxtFDirectorTesis.getText().toUpperCase();
        String lugarTrabajo = jTxtFLugarTrabajo.getText().toUpperCase();
        String hrTrabajo = jTxtFHrTrabajo.getText().toUpperCase();
        
        //se quita el error de convertir la cadena vacia por un entero
        String valor = jTxtFCelular.getText();
        
        if(valor.equals("")){
            valor = "0";
        }
        
        int celular = Integer.parseInt(valor);
        
        //Se crea un objeto candidato para guardarlo en la base de datos.
        Candidato candidato = new Candidato(foto, nombre, apellidoPaterno, apellidoMaterno, contrasena, carrera, temaTesis, cartaCompromiso, cartaMotivos);
        candidato.setMatricula(matricula);
        candidato.setEmail(email);
        candidato.setCelular(celular);
        candidato.setCreditos(creditos);
        candidato.setDirectorTesis(directorTesis);
        candidato.setLugarTrabajo(lugarTrabajo);
        candidato.setHorarioTrabajo(hrTrabajo);
        
        //Se guarda al candidato en la base de datos y se muestra un mensaje si fue exitosa o no la transacción.
        if(helper.Registrar(candidato)){
            JOptionPane.showMessageDialog(this, "Estas registrado en el sistema", "Registro exitosamente", JOptionPane.INFORMATION_MESSAGE);
            Grupos ventana = new Grupos();
            ventana.setLocationRelativeTo(this);
            ventana.show();        
            this.dispose();
        }
        
        JOptionPane.showMessageDialog(this, "Error en el sistema", "Registro fallido", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jBtAceptarActionPerformed

    private void jBtCartaCompromisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCartaCompromisoActionPerformed
        //Se abre una ventana para navegar entre nuestros directorios.
        JFileChooser directorios = new JFileChooser();
        //Se coloca un filtro para que solo muestre archivos .pdf .
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos .pdf", "pdf");
        directorios.setFileFilter(filtro);
        
        int resultado = directorios.showSaveDialog(this);
        
        //Si se da aceptar en la ventana de directorios se guarda la dirección.
        if(resultado == JFileChooser.APPROVE_OPTION){        
            cartaCompromiso = directorios.getSelectedFile();
            jLbCartaCompromiso.setText(cartaCompromiso.getName());
        }        
    }//GEN-LAST:event_jBtCartaCompromisoActionPerformed

    private void jBtCartaMotivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCartaMotivosActionPerformed
        //Se abre una ventana para navegar entre nuestros directorios.
        JFileChooser directorios = new JFileChooser();
        //Se coloca un filtro para que solo muestre archivos .pdf .
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos .pdf", "pdf");
        directorios.setFileFilter(filtro);
        
        int resultado = directorios.showSaveDialog(this);
        
        //Si se da aceptar en la ventana de directorios se guarda la dirección.
        if(resultado == JFileChooser.APPROVE_OPTION){        
            cartaMotivos = directorios.getSelectedFile();
            jLbCartaMotivos.setText(cartaMotivos.getName());
        }
    }//GEN-LAST:event_jBtCartaMotivosActionPerformed

    private void jLbFotoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbFotoMousePressed
        //Se abre una ventana para navegar entre nuestros directorios.
        JFileChooser directorios = new JFileChooser();
        //Se coloca un filtro para que solo muestre imagenes .jpg y .png .
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Foto .jpg .png", "jpg", "png");
        directorios.setFileFilter(filtro);
        
        int resultado = directorios.showSaveDialog(this);
        
        //Si se da aceptar en la ventana de directorios se guarda la dirección y se muestra la imagen.
        if(resultado == JFileChooser.APPROVE_OPTION){        
            File archivo = directorios.getSelectedFile();
            ImageIcon foto = new ImageIcon(archivo.toString());
            //Se ajusta el tamaño de la foto al jLabel "jLbFoto"
            Icon icono = new ImageIcon(foto.getImage().getScaledInstance(jLbFoto.getWidth(), jLbFoto.getHeight(), Image.SCALE_DEFAULT));
            jLbFoto.setIcon(icono);
        }
    }//GEN-LAST:event_jLbFotoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroCandidato().setVisible(true);
            }
        });
    }
    
    /*
    * Vista por default.
    */
    private void Inicio(){
        ImageIcon imagen = new ImageIcon("foto.png");
        jLbFoto.setText("");
        jLbFoto.setIcon(imagen);
        Trabajo(false);
        jLbCartaMotivos.setText("");
        jLbCartaCompromiso.setText("");
        jTxtFGeneracion.enable(false);
        
        //se pone un valor mínimo y formato al campo creditos.
        SpinnerNumberModel spinner = new SpinnerNumberModel(0, 0, 100, 1);
        jSpnCreditos.setModel(spinner);        
    }
    
    /**
     * Maneja la visibilidad de las cajas de texto y etiquetas de "Lugar de trabajo" y "Horario de trabajo".
     */
    private void Trabajo(boolean respuesta){        
        jLbHrTrabajo.setVisible(respuesta);
        jTxtFHrTrabajo.setVisible(respuesta);
        jLbLugarTrabajo.setVisible(respuesta);
        jTxtFLugarTrabajo.setVisible(respuesta);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btGroupTrabaja;
    private javax.swing.JButton jBtAceptar;
    private javax.swing.JButton jBtAtras;
    private javax.swing.JButton jBtCartaCompromiso;
    private javax.swing.JButton jBtCartaMotivos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLbCartaCompromiso;
    private javax.swing.JLabel jLbCartaMotivos;
    private javax.swing.JLabel jLbFoto;
    private javax.swing.JLabel jLbHrTrabajo;
    private javax.swing.JLabel jLbLugarTrabajo;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JRadioButton jRadBtNo;
    private javax.swing.JRadioButton jRadBtSi;
    private javax.swing.JSpinner jSpnCreditos;
    private javax.swing.JTextField jTxtFApMaterno;
    private javax.swing.JTextField jTxtFApPaterno;
    private javax.swing.JTextField jTxtFCarrera;
    private javax.swing.JTextField jTxtFCelular;
    private javax.swing.JTextField jTxtFDirectorTesis;
    private javax.swing.JTextField jTxtFEmail;
    private javax.swing.JTextField jTxtFGeneracion;
    private javax.swing.JTextField jTxtFHrTrabajo;
    private javax.swing.JTextField jTxtFLugarTrabajo;
    private javax.swing.JTextField jTxtFMatricula1;
    private javax.swing.JTextField jTxtFMatricula2;
    private javax.swing.JTextField jTxtFMatricula3;
    private javax.swing.JTextField jTxtFNombre;
    private javax.swing.JTextField jTxtFTemaTesis;
    // End of variables declaration//GEN-END:variables
}
